apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ra7kr7xhu-go 
  janus-idp.io/tekton: ra7kr7xhu-go
  backstage.io/kubernetes-id: ra7kr7xhu-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ra7kr7xhu-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml