apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ra7kr7xhu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ra7kr7xhu-go 
  name: ra7kr7xhu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ra7kr7xhu-go 
